# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: MÚSIC FM
email: geral@fantasfm.com
description: > # A MÚSICA BOA PASSA AQUI
baseurl: "" # the subpath of your site, e.g. /blog
url: http://nonstop.fantasfm.com/ # the base hostname & protocol for your site
twitter_username: 
# github_username: jekyll

#Build settings
markdown: kramdown
source:      site
destination: target
