#!/bin/bash -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR

bundle exec jekyll build

set +e
git add .
git commit -m "$(whoami) enviar"
git push
set -e

# upload
aws s3 sync --delete target s3://nonstop.fantasfm.com/
