#!/bin/bash -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR

jekyll build

set +e
git add .
git commit -m "$(whoami) enviar"
git push
set -e

aws s3 cp --recursive target s3://nonstop.fantasfm.com/
